pipeline:
  build:
    image: node:${NODE_VERSION}
    environment:
      - NODE_ENV=test
    commands:
      - yarn 2> /dev/null
      - yarn test
matrix:
  NODE_VERSION:
    - 4
    - 6
    - 7
    - 8
    - 9
    - 10
